#!/usr/bin/env python
"""
Coreference overlay — Step 2 of identity resolution (the residual Fix 1 could not do).

Fix 1 (`aliases.txt`) merges spelling variants GLOBALLY — safe only when one surface always means
one figure. The residual is the opposite case: an UNDER-SPECIFIED label (bare `Guido`, `Latino`,
`Pietro`) that means DIFFERENT figures in different scenes, so no global alias is correct. This pass
decides, per SCENE and with the scene's context, which fuller-form figure (if any) an under-specified
label refers to, and writes a per-tag correction to `04-tags/coref.txt`.

Why per-tag at the tag layer, not in the registry: the downstream join `raw_to_canonical` is a
global `fold_key -> canonical` map and CANNOT route one surface to two nodes. The disambiguation has
to live in the label itself, applied where every consumer reads it (`load_tags`). Once a tag's label
is identity-first, the existing fold_key join folds it onto the right node automatically — no change
to 06/08/11.

This is the ONLY step here that calls the model, and it CANNOT be structurally verified (a wrong
merge passes every check). So its output is staged in `04-tags/coref.txt` for human review before
commit, and every decision (including "distinct") is recorded in `coref.cache.txt` for resume and
audit. Run it, READ the proposals, delete the wrong ones, then rebuild the registry.

Granularity: one decision per (label, canticle, canto, scene), applied to every occurrence of that
label in the scene — 04-tags already aims for intra-scene label consistency, so a scene's `Guido` is
one figure. The candidate targets for a bare label are the fuller individual nodes that contain it as
a token (`Guido` -> `Guido da Montefeltro`, …; `Latino` -> `Brunetto Latino`), plus a small seed map
for semantic pairs no token test catches (`Iesù` -> `Cristo`).

Run it as ONE process — do NOT parallelize per canticle (same hazard as registry.py). Both outputs
are GLOBAL single files with no locking: `coref.cache.txt` is append-on-decision (concurrent appends
corrupt it), and `coref.txt` is rewritten WHOLE from the in-memory cache at the end of the run, so a
second process clobbers the first's corrections (last-writer-wins). The intended invocation is the
single `coreference.py inferno purgatorio paradiso` that `make -C 05-registry coref` runs.

Input:  04-tags/<canticle>/NN.txt    (committed; the labels to correct)
        05-registry/<canticle>.txt   (committed; the node set = candidate targets)
        03-reading/<canticle>/NN.txt  (scene context for the judgment)
Output: 04-tags/coref.txt            (the overlay, human-reviewable)
        05-registry/coref.cache.txt  (resume + audit cache; every decision incl. "distinct")
"""
import argparse
import re
import sys

from dante_analyze import (
    REGISTRY_DIR, TAGS_DIR, MAX_LENGTH,
    read_markup, load_tags, load_readings, load_registry, number_scene,
    norm_label, call_llm, step_sep,
)

CANTICLES = ("inferno", "purgatorio", "paradiso")
DISTINCT = "distinct"
DEFAULT_MODEL = "ollama:gemma4:31b-it-qat"
COREF_FILE = TAGS_DIR / "coref.txt"
COREF_CACHE = REGISTRY_DIR / "coref.cache.txt"

# Semantic merge targets a token test cannot catch (bare label -> candidate canonicals).
SEED_TARGETS = {
    "Iesù": ["Cristo"],
}

COREF_HEADER = (
    "# Per-tag coreference overlay: canticle/canto/start-end/tag_no = identity-first label\n"
    "# Upgrades under-specified 04-tags labels (bare names, periphrases) to their identity-first\n"
    "# form, applied at load_tags() so every consumer sees the same per-tag identity.\n"
    "# Generated by 05-registry/coreference.py; human-reviewable before committing.\n"
)


def committed_cantos(canticle):
    """Cantos with a committed 04-tags file, in order."""
    d = TAGS_DIR / canticle
    if not d.is_dir():
        return []
    return sorted(int(p.stem) for p in d.glob("[0-9][0-9].txt"))


# ---------- candidates ----------

def candidate_targets(registry):
    """{bare_label: [fuller canonical, …]} — under-specified individual nodes paired with the fuller
    individual nodes they could resolve to. A bare label is a single-token `individual` canonical; a
    target is a multi-token `individual` canonical containing that token (plus SEED_TARGETS)."""
    individuals = [c for c, n in registry.items() if n.get("type") == "individual"]
    bare = [c for c in individuals if " " not in c]
    out = {}
    for b in bare:
        targets = sorted(c for c in individuals if c != b and b in c.split())
        for extra in SEED_TARGETS.get(b, []):
            if extra in registry and extra not in targets:
                targets.append(extra)
        if targets:
            out[b] = targets
    return out


def gather_occurrences(canticle, bare_labels):
    """{(label, canto, s, e): [tag_no, …]} for every scene where a candidate bare label occurs.
    Reads through load_tags, so a tag already corrected in the overlay no longer matches (skipped)."""
    occ = {}
    wanted = {norm_label(b): b for b in bare_labels}
    for canto in committed_cantos(canticle):
        for (s, e), res in load_tags(canticle, canto, apply_coref=False).items():
            for tag_no, raw in res.items():
                b = wanted.get(norm_label(raw))
                if b is not None:
                    occ.setdefault((b, canto, s, e), []).append(tag_no)
    return occ


# ---------- resume cache ----------

CACHE_RE = re.compile(r"^\s*(\w+)/(\d+)/(\d+)-(\d+)\s+(.*\S)\s*=\s*(.*\S)\s*$")


def load_cache():
    """{(canticle, canto, s, e, label): decision} from coref.cache.txt (decision = a canonical or
    'distinct')."""
    out = {}
    if COREF_CACHE.exists():
        for line in COREF_CACHE.read_text(encoding="utf-8").splitlines():
            m = CACHE_RE.match(line)
            if m:
                canticle, canto, s, e = m.group(1), int(m.group(2)), int(m.group(3)), int(m.group(4))
                out[(canticle, canto, s, e, m.group(5))] = m.group(6)
    return out


def append_cache(canticle, canto, s, e, label, decision):
    with COREF_CACHE.open("a", encoding="utf-8") as f:
        f.write(f"{canticle}/{canto}/{s}-{e} {label} = {decision}\n")


def write_overlay(cache):
    """Regenerate 04-tags/coref.txt from the cache: per-tag lines for every non-'distinct' decision.
    Re-reads each scene RAW (apply_coref=False) to expand a (label, scene) decision to the tag
    numbers that carry the bare label."""
    by_scene = {}   # (canticle, canto, s, e) -> {norm_label: decision}
    for (canticle, canto, s, e, label), decision in cache.items():
        if decision != DISTINCT:
            by_scene.setdefault((canticle, canto, s, e), {})[norm_label(label)] = decision
    lines = []
    for (canticle, canto, s, e) in sorted(by_scene):
        res = load_tags(canticle, canto, apply_coref=False).get((s, e), {})
        for tag_no in sorted(res):
            decision = by_scene[(canticle, canto, s, e)].get(norm_label(res[tag_no]))
            if decision:
                lines.append(f"{canticle}/{canto}/{s}-{e}/{tag_no} = {decision}")
    COREF_FILE.write_text(COREF_HEADER + "\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


# ---------- LLM ----------

def build_prompt(label, targets, source_text, reading):
    """Ask which fuller figure (if any) `label` denotes in THIS scene. Source text + reading are
    scene context; the candidate list is general knowledge about who shares the name. No per-item
    answer is supplied — the model must read the scene."""
    listing = "\n".join(f"{i}. {t}" for i, t in enumerate(targets, 1))
    return f"""In one scene of Dante's Divine Comedy a figure is referred to by the under-specified
label "{label}". Several distinct figures in the poem share that name; decide which one — if any —
"{label}" refers to IN THIS SCENE, using the scene below.

Scene (source text):
{source_text}

Scene (reading):
{reading}

Candidates that "{label}" could be (figures elsewhere in the poem bearing this name):
{listing}
{len(targets) + 1}. {DISTINCT} — none of the above; "{label}" here is a different or unidentifiable figure.

Answer with exactly one line:

    {label} = <one candidate exactly as listed, or {DISTINCT}>

Echo "{label}" verbatim. Output only that one line and nothing else."""


ANSWER_RE = re.compile(r"^\s*(.*\S)\s*=\s*(.*\S)\s*$")


def parse_answer(text, label, targets):
    """The chosen decision (a target canonical or DISTINCT), or None if unparseable/invalid."""
    for raw in text.splitlines():
        m = ANSWER_RE.match(raw)
        if not m:
            continue
        if norm_label(m.group(1)) != norm_label(label):
            continue
        choice = m.group(2).strip()
        if choice == DISTINCT:
            return DISTINCT
        for t in targets:
            if norm_label(choice) == norm_label(t):
                return t
    return None


def decide(label, targets, source_text, reading, model, max_attempts=3):
    """One scene decision, retried in-conversation until parseable, else DISTINCT (the safe default:
    no correction, leave the label as committed)."""
    messages = [{"role": "user", "content": build_prompt(label, targets, source_text, reading)}]
    step_sep("coreference")
    resp = call_llm(messages, model, include_thoughts=True)
    for attempt in range(1, max_attempts + 1):
        decision = parse_answer(resp.text, label, targets)
        if decision is not None:
            return decision
        if attempt >= max_attempts:
            break
        messages += [
            {"role": "assistant", "content": resp.text},
            {"role": "user", "content": f'Answer again with one line `{label} = <candidate or '
                                         f'{DISTINCT}>`, the candidate echoed exactly as listed.'},
        ]
        resp = call_llm(messages, model, max_length=MAX_LENGTH, include_thoughts=True)
    print(f"coref: {label}: unparseable after {max_attempts} attempts; defaulting to {DISTINCT}",
          file=sys.stderr)
    return DISTINCT


# ---------- driver ----------

def main():
    ap = argparse.ArgumentParser(
        description="Coreference overlay (KG identity Step 2): resolve under-specified labels "
                    "per scene (see 05-registry/README.md).",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("canticles", nargs="*", default=list(CANTICLES),
                    help="canticles to process (default: all three)")
    ap.add_argument("-m", "--model", default=DEFAULT_MODEL,
                    help=f"LLM for the coreference judgment (default: {DEFAULT_MODEL})")
    args = ap.parse_args()

    cache = load_cache()
    for canticle in args.canticles:
        registry = load_registry(canticle)
        targets_of = candidate_targets(registry)
        occ = gather_occurrences(canticle, list(targets_of))
        scenes = sorted(occ)
        print(f"coref {canticle}: {len(targets_of)} candidate label(s), {len(scenes)} scene(s) to "
              f"decide", file=sys.stderr)
        for (label, canto, s, e) in scenes:
            ck = (canticle, canto, s, e, label)
            if ck in cache:
                continue
            markup = read_markup(canticle, canto)
            source_text, _k, _meta = number_scene(markup, s, e)
            reading = load_readings(canticle, canto).get((s, e), "")
            decision = decide(label, targets_of[label], source_text, reading, args.model)
            append_cache(canticle, canto, s, e, label, decision)
            cache[ck] = decision
            mark = decision if decision != DISTINCT else "(distinct — no correction)"
            print(f"coref {canticle} {canto} {s}-{e}: {label} -> {mark}", file=sys.stderr)

    write_overlay(cache)
    n = sum(1 for v in cache.values() if v != DISTINCT)
    print(f"coref: {n} correction(s) written to {COREF_FILE} (review before committing)",
          file=sys.stderr)


if __name__ == "__main__":
    main()
